//package GFG.OOPS.KK_04.notes;
//
//public class txt {
//
//  ACCESS MODIFIERS
//
// PUBLIC->CLASS,PACKAGE,SUBCLASS IN SAME PACKAGE,SUBCLASS IN DIFF PKG,OUTSIDE PKG N OUTSIDE SUBCLASS
// PROTECTED->CLASS,PKG,SUBCLASS SAME PKG, SUBCLASS DIFF PKG
// NO MODIFIER->CLASS,PKG,SUBCLASS SAME PKG
// PRIVATE->CLASS
//
//
// }
